name: Build APK from ZIP

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"
          yes | sdkmanager --licenses

      - name: Unzip project
        run: unzip -o "BFA-LSPosed-Module-CI.zip" -d "$GITHUB_WORKSPACE"

      # Pakai Gradle tanpa gradlew (wrapper), versi dari action
      - name: Use Gradle 8.x
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Build debug APK
        run: gradle assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
